# Generated by Django 4.0.4 on 2022-04-14 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_caso', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_demanda', models.IntegerField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField()),
                ('tipodemanda', models.CharField(max_length=30)),
                ('detalle', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legaltech.caso')),
            ],
        ),
        migrations.CreateModel(
            name='Demandante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField()),
                ('dv', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legaltech.demanda')),
            ],
        ),
        migrations.CreateModel(
            name='Demandado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField()),
                ('dv', models.IntegerField()),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('telefono', models.IntegerField()),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legaltech.demanda')),
            ],
        ),
    ]
